version: '2'

services:
  nginx:
    image: bitnami/nginx:1.12.1-r1
    volumes:
      - ./dev/nginx:/bitnami/nginx/conf/vhosts
    depends_on:
      - backend
      - frontend
    environment:
      - VIRTUAL_HOST=fortress.docker
      - VIRTUAL_PORT=8080
    ports:
      - 8080:8080
  mongo:
    image: bitnami/mongodb:3.4.9-r1
  backend:
    image: angelrb/fortress:latest
    command: yarn dev
    entrypoint: /scripts/entrypoint.sh
    env_file:
     - .env.development
    depends_on:
      - mongo
    volumes:
      - ./:/app
      - ./scripts:/scripts
      - /app/node_modules
    ports:
      - 5858:5858
    environment:
      - NODE_ENV=development
  frontend:
    image: angelrb/fortress:latest
    command: yarn start
    entrypoint: /scripts/entrypoint.sh
    volumes:
      - ./client:/app
      - ./scripts:/scripts
      - /app/node_modules
    environment:
      - NODE_ENV=development
